apiVersion: apps/v1 # String
kind: Deployment  # String
metadata: # Dictionary
  namespace: kings
  name: python-deployment # Name
  labels: # Dictionary 
    app: python
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python
  template:  
    metadata:
      labels: 
        app: python
    spec:
        containers: # List
          - name: python
            image: vijayasurya/python:v2.1
            ports:  # List
              - containerPort: 9000
            env:
              - name: DBHOST
                value: "mysql-service"
              - name: DBPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kings-secret
                    key: ombhimphat
              - name: DBUSER
                value: "root"
              - name: DBPORT
                value: "3306"